package com.github.dmadapter.cli;

import com.github.dmadapter.core.DmAdapterException;
import com.github.dmadapter.core.FileChange;
import com.github.dmadapter.core.MapperXmlFile;
import com.github.dmadapter.mybatis.MapperXmlScanner;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.InputSource;

import javax.xml.XMLConstants;
import javax.xml.parsers.DocumentBuilderFactory;
import java.io.IOException;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Stream;

class DmSqlValidationTestGenerator {
    static final String DEFAULT_CONFIG_PATH = ".dm-adapter/sql-validation.yml";
    static final String TEST_CLASS_NAME = "DmSqlValidationTest";

    private final ApplicationModuleSelector applicationModuleSelector;
    private final MapperXmlScanner mapperXmlScanner;

    DmSqlValidationTestGenerator() {
        this(new ApplicationModuleSelector(), new MapperXmlScanner());
    }

    DmSqlValidationTestGenerator(ApplicationModuleSelector applicationModuleSelector, MapperXmlScanner mapperXmlScanner) {
        this.applicationModuleSelector = applicationModuleSelector;
        this.mapperXmlScanner = mapperXmlScanner;
    }

    ValidationTestGenerationResult generate(Path projectRoot, Path appModule, Path mapperDir, Path configPath, String schema) {
        Path normalizedRoot = projectRoot.toAbsolutePath().normalize();
        ApplicationModule applicationModule = applicationModuleSelector.select(normalizedRoot, appModule);
        Path actualConfigPath = resolveProjectPath(normalizedRoot, configPath, DEFAULT_CONFIG_PATH);
        Path testPath = testPath(applicationModule);

        List<FileChange> fileChanges = new ArrayList<>();
        List<String> warnings = new ArrayList<>();
        writeIfMissing(
                actualConfigPath,
                configTemplate(discoveredMapperStatements(normalizedRoot, mapperDir), schema),
                "Generate Dameng SQL validation parameter configuration",
                fileChanges,
                warnings
        );
        writeIfMissing(
                testPath,
                javaTestSource(applicationModule.packageName()),
                "Generate Dameng SQL validation JUnit test",
                fileChanges,
                warnings
        );
        return new ValidationTestGenerationResult(actualConfigPath, testPath, fileChanges, warnings);
    }

    private Path resolveProjectPath(Path projectRoot, Path configuredPath, String defaultRelativePath) {
        if (configuredPath == null) {
            return projectRoot.resolve(defaultRelativePath).toAbsolutePath().normalize();
        }
        if (configuredPath.isAbsolute()) {
            return configuredPath.toAbsolutePath().normalize();
        }
        return projectRoot.resolve(configuredPath).toAbsolutePath().normalize();
    }

    private Path testPath(ApplicationModule applicationModule) {
        Path testRoot = applicationModule.moduleRoot().resolve("src/test/java");
        if (applicationModule.packageName().isBlank()) {
            return testRoot.resolve(TEST_CLASS_NAME + ".java").toAbsolutePath().normalize();
        }
        return testRoot.resolve(applicationModule.packageName().replace('.', '/'))
                .resolve(TEST_CLASS_NAME + ".java")
                .toAbsolutePath()
                .normalize();
    }

    private void writeIfMissing(
            Path path,
            String content,
            String description,
            List<FileChange> fileChanges,
            List<String> warnings
    ) {
        if (Files.exists(path)) {
            warnings.add("Skipped generation because file already exists: " + path);
            return;
        }
        try {
            Files.createDirectories(path.getParent());
            Files.writeString(path, content, StandardCharsets.UTF_8);
            fileChanges.add(FileChange.applied(path.toString(), "CREATE", description));
        } catch (IOException e) {
            throw new DmAdapterException("Failed to write generated file: " + path, e);
        }
    }

    private String configTemplate(List<String> mapperStatements, String schema) {
        StringBuilder content = new StringBuilder();
        content.append("""
                # Generated by dm-adapter.
                # Run in the Dameng test environment, for example:
                # DM_SQL_VALIDATION=true mvn -Dtest=DmSqlValidationTest test
                #
                """);
        if (schema == null || schema.isBlank()) {
            content.append("""
                    # Optional Dameng schema. Quoted schema names such as sample-system are supported.
                    # schema: "sample-system"

                    """);
        } else {
            content.append("schema: \"").append(escapeYamlScalar(schema.trim())).append("\"\n\n");
        }
        content.append("""
                # Configure sample method arguments by mapperClass.method.
                # Missing methods are invoked with conservative generated parameters when possible.
                methods:
                  # com.example.UserMapper.selectById:
                  #   args:
                  #     - 1
                
                # Methods listed here are skipped by the generated integration test.
                excludedMethods:
                  # - com.example.UserMapper.deleteAll
                """);
        if (!mapperStatements.isEmpty()) {
            content.append("\n# Discovered mapper statements:\n");
            for (String mapperStatement : mapperStatements) {
                content.append("# - ").append(mapperStatement).append("\n");
            }
        }
        return content.toString();
    }

    private String escapeYamlScalar(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private List<String> discoveredMapperStatements(Path projectRoot, Path mapperDir) {
        List<Path> mapperPaths = mapperDir == null
                ? mapperXmlScanner.scan(projectRoot).stream().map(MapperXmlFile::path).map(Path::of).toList()
                : xmlFiles(resolveProjectPath(projectRoot, mapperDir, ""));
        Set<String> statements = new LinkedHashSet<>();
        for (Path mapperPath : mapperPaths) {
            statements.addAll(mapperStatements(mapperPath));
        }
        return statements.stream().sorted().toList();
    }

    private List<Path> xmlFiles(Path directory) {
        if (!Files.isDirectory(directory)) {
            return List.of();
        }
        try (Stream<Path> paths = Files.walk(directory)) {
            return paths.filter(Files::isRegularFile)
                    .filter(path -> path.getFileName().toString().endsWith(".xml"))
                    .sorted()
                    .toList();
        } catch (IOException e) {
            throw new DmAdapterException("Failed to scan mapper XML files under " + directory, e);
        }
    }

    private List<String> mapperStatements(Path mapperPath) {
        try {
            Document document = parseXml(mapperPath);
            Element root = document.getDocumentElement();
            if (root == null || !"mapper".equals(root.getTagName())) {
                return List.of();
            }
            String namespace = root.getAttribute("namespace");
            if (namespace == null || namespace.isBlank()) {
                return List.of();
            }
            List<String> statements = new ArrayList<>();
            NodeList children = root.getChildNodes();
            for (int i = 0; i < children.getLength(); i++) {
                Node node = children.item(i);
                if (node instanceof Element element && isStatementElement(element)) {
                    String id = element.getAttribute("id");
                    if (id != null && !id.isBlank()) {
                        statements.add(namespace + "." + id);
                    }
                }
            }
            statements.sort(Comparator.naturalOrder());
            return statements;
        } catch (Exception e) {
            return List.of();
        }
    }

    private boolean isStatementElement(Element element) {
        return "select".equals(element.getTagName())
                || "insert".equals(element.getTagName())
                || "update".equals(element.getTagName())
                || "delete".equals(element.getTagName());
    }

    private Document parseXml(Path path) throws Exception {
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        factory.setNamespaceAware(false);
        factory.setXIncludeAware(false);
        factory.setExpandEntityReferences(false);
        enableFeature(factory, XMLConstants.FEATURE_SECURE_PROCESSING, true);
        enableFeature(factory, "http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
        enableFeature(factory, "http://xml.org/sax/features/external-general-entities", false);
        enableFeature(factory, "http://xml.org/sax/features/external-parameter-entities", false);
        try (Reader reader = Files.newBufferedReader(path, StandardCharsets.UTF_8)) {
            return factory.newDocumentBuilder().parse(new InputSource(reader));
        }
    }

    private void enableFeature(DocumentBuilderFactory factory, String feature, boolean enabled) {
        try {
            factory.setFeature(feature, enabled);
        } catch (Exception ignored) {
            // XML parser support varies by JDK distribution; unsupported hardening flags are skipped.
        }
    }

    private String javaTestSource(String packageName) {
        String packageDeclaration = packageName == null || packageName.isBlank()
                ? ""
                : "package " + packageName + ";\n\n";
        return TEST_TEMPLATE.replace("__PACKAGE_DECLARATION__", packageDeclaration);
    }

    private static final String TEST_TEMPLATE = """
            __PACKAGE_DECLARATION__import org.apache.ibatis.annotations.Mapper;
            import org.junit.jupiter.api.Tag;
            import org.junit.jupiter.api.Test;
            import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
            import org.springframework.beans.factory.ListableBeanFactory;
            import org.springframework.beans.factory.annotation.Autowired;
            import org.springframework.boot.test.context.SpringBootTest;
            import org.springframework.jdbc.datasource.DataSourceUtils;
            import org.springframework.test.context.ActiveProfiles;
            import org.springframework.transaction.PlatformTransactionManager;
            import org.springframework.transaction.support.TransactionTemplate;
            
            import javax.sql.DataSource;
            import java.io.IOException;
            import java.lang.reflect.Array;
            import java.lang.reflect.Constructor;
            import java.lang.reflect.Field;
            import java.lang.reflect.InvocationTargetException;
            import java.lang.reflect.Method;
            import java.lang.reflect.Modifier;
            import java.lang.reflect.ParameterizedType;
            import java.lang.reflect.Type;
            import java.math.BigDecimal;
            import java.math.BigInteger;
            import java.nio.charset.StandardCharsets;
            import java.nio.file.Files;
            import java.nio.file.Path;
            import java.sql.Connection;
            import java.sql.Statement;
            import java.time.Instant;
            import java.time.LocalDate;
            import java.time.LocalDateTime;
            import java.time.LocalTime;
            import java.util.ArrayList;
            import java.util.Collection;
            import java.util.Comparator;
            import java.util.Date;
            import java.util.LinkedHashMap;
            import java.util.LinkedHashSet;
            import java.util.List;
            import java.util.Locale;
            import java.util.Map;
            import java.util.Optional;
            import java.util.Properties;
            import java.util.Set;
            import java.util.UUID;
            import java.util.stream.Collectors;
            
            import static org.junit.jupiter.api.Assertions.fail;
            
            @SpringBootTest
            @ActiveProfiles("dm")
            @Tag("dm-sql-validation")
            @EnabledIfEnvironmentVariable(named = "DM_SQL_VALIDATION", matches = "true")
            class DmSqlValidationTest {
                private static final String CONFIG_PATH = ".dm-adapter/sql-validation.yml";
                private static final String MARKDOWN_REPORT = ".dm-adapter/sql-validation-report.md";
                private static final String JSON_REPORT = ".dm-adapter/sql-validation-report.json";
            
                @Autowired
                private ListableBeanFactory beanFactory;
            
                @Autowired(required = false)
                private PlatformTransactionManager transactionManager;

                @Autowired(required = false)
                private DataSource dataSource;

                @Test
                void validateMappedDaoSql() throws Exception {
                    Path projectRoot = findProjectRoot();
                    ValidationConfig config = ValidationConfig.load(projectRoot.resolve(CONFIG_PATH));
                    List<ValidationRecord> records = new ArrayList<>();
                    List<MapperMethod> mapperMethods = mapperMethods();
                    if (mapperMethods.isEmpty()) {
                        records.add(ValidationRecord.failed("(discovery)", "none", "No MyBatis mapper or DAO beans were found."));
                    }
                    for (MapperMethod mapperMethod : mapperMethods) {
                        if (config.excludes(mapperMethod.key())) {
                            records.add(ValidationRecord.skipped(mapperMethod.key(), "excluded", "Excluded by sql-validation.yml."));
                            continue;
                        }
                        ParameterResolution parameters = resolveParameters(mapperMethod, config);
                        if (!parameters.resolved) {
                            records.add(ValidationRecord.skipped(mapperMethod.key(), parameters.source, parameters.message));
                            continue;
                        }
                        records.add(invokeMapperMethod(mapperMethod, parameters, config));
                    }
            
                    writeReports(projectRoot, records);
                    List<ValidationRecord> failed = records.stream()
                            .filter(record -> "FAILED".equals(record.status))
                            .collect(Collectors.toList());
                    if (!failed.isEmpty()) {
                        fail("Dameng SQL validation failed for " + failed.size()
                                + " mapper methods. See " + projectRoot.resolve(MARKDOWN_REPORT));
                    }
                }
            
                private List<MapperMethod> mapperMethods() {
                    List<MapperMethod> mapperMethods = new ArrayList<>();
                    Set<String> seen = new LinkedHashSet<>();
                    for (String beanName : beanFactory.getBeanDefinitionNames()) {
                        Object bean;
                        try {
                            bean = beanFactory.getBean(beanName);
                        } catch (Exception ignored) {
                            continue;
                        }
                        Set<Class<?>> interfaces = new LinkedHashSet<>();
                        collectInterfaces(bean.getClass(), interfaces);
                        for (Class<?> mapperInterface : interfaces) {
                            if (!isCandidateMapperInterface(mapperInterface)) {
                                continue;
                            }
                            for (Method method : mapperInterface.getMethods()) {
                                if (isInvocableMapperMethod(method)) {
                                    String signature = mapperInterface.getName() + "." + method.getName()
                                            + "(" + parameterTypeNames(method) + ")";
                                    if (seen.add(signature)) {
                                        mapperMethods.add(new MapperMethod(bean, mapperInterface, method));
                                    }
                                }
                            }
                        }
                    }
                    mapperMethods.sort(Comparator.comparing(MapperMethod::key)
                            .thenComparing(mapperMethod -> mapperMethod.method.toGenericString()));
                    return mapperMethods;
                }
            
                private void collectInterfaces(Class<?> type, Set<Class<?>> interfaces) {
                    if (type == null || Object.class.equals(type)) {
                        return;
                    }
                    for (Class<?> candidate : type.getInterfaces()) {
                        if (interfaces.add(candidate)) {
                            collectInterfaces(candidate, interfaces);
                        }
                    }
                    collectInterfaces(type.getSuperclass(), interfaces);
                }
            
                private boolean isCandidateMapperInterface(Class<?> mapperInterface) {
                    String simpleName = mapperInterface.getSimpleName();
                    return mapperInterface.isInterface()
                            && (mapperInterface.isAnnotationPresent(Mapper.class)
                            || simpleName.endsWith("Mapper")
                            || simpleName.endsWith("Dao"));
                }
            
                private boolean isInvocableMapperMethod(Method method) {
                    int modifiers = method.getModifiers();
                    return !method.isSynthetic()
                            && !method.isBridge()
                            && !method.isDefault()
                            && !Modifier.isStatic(modifiers)
                            && !Object.class.equals(method.getDeclaringClass());
                }
            
                private ParameterResolution resolveParameters(MapperMethod mapperMethod, ValidationConfig config) {
                    List<String> configuredArgs = config.methodArgs.get(mapperMethod.key());
                    if (configuredArgs != null) {
                        return configuredParameters(mapperMethod, configuredArgs);
                    }
                    return generatedParameters(mapperMethod);
                }
            
                private ParameterResolution configuredParameters(MapperMethod mapperMethod, List<String> configuredArgs) {
                    Class<?>[] parameterTypes = mapperMethod.method.getParameterTypes();
                    if (configuredArgs.size() != parameterTypes.length) {
                        return ParameterResolution.unresolved(
                                "configured",
                                "Configured argument count " + configuredArgs.size()
                                        + " does not match method parameter count " + parameterTypes.length + "."
                        );
                    }
                    Object[] args = new Object[parameterTypes.length];
                    for (int i = 0; i < parameterTypes.length; i++) {
                        ValueResult value = convertScalar(configuredArgs.get(i), parameterTypes[i], mapperMethod.method.getGenericParameterTypes()[i]);
                        if (!value.resolved) {
                            return ParameterResolution.unresolved("configured", value.message);
                        }
                        args[i] = value.value;
                    }
                    return ParameterResolution.resolved("configured", args);
                }
            
                private ParameterResolution generatedParameters(MapperMethod mapperMethod) {
                    Class<?>[] parameterTypes = mapperMethod.method.getParameterTypes();
                    Type[] genericTypes = mapperMethod.method.getGenericParameterTypes();
                    Object[] args = new Object[parameterTypes.length];
                    for (int i = 0; i < parameterTypes.length; i++) {
                        ValueResult value = defaultValue(parameterTypes[i], genericTypes[i], 0);
                        if (!value.resolved) {
                            return ParameterResolution.unresolved("auto", value.message);
                        }
                        args[i] = value.value;
                    }
                    return ParameterResolution.resolved("auto", args);
                }
            
                private ValidationRecord invokeMapperMethod(
                        MapperMethod mapperMethod,
                        ParameterResolution parameters,
                        ValidationConfig config
                ) {
                    if (transactionManager == null && isWriteLikeMethod(mapperMethod.method)) {
                        return ValidationRecord.skipped(
                                mapperMethod.key(),
                                parameters.source,
                                "Write-like method skipped because no PlatformTransactionManager bean was available."
                        );
                    }
                    try {
                        Object result;
                        if (transactionManager != null) {
                            TransactionTemplate transactionTemplate = new TransactionTemplate(transactionManager);
                            result = transactionTemplate.execute(status -> {
                                status.setRollbackOnly();
                                applySchema(config);
                                return invokeReflectively(mapperMethod, parameters.args);
                            });
                        } else {
                            applySchema(config);
                            result = invokeReflectively(mapperMethod, parameters.args);
                        }
                        return ValidationRecord.passed(mapperMethod.key(), parameters.source, resultSummary(result));
                    } catch (MapperInvocationException e) {
                        return ValidationRecord.failed(mapperMethod.key(), parameters.source, throwableSummary(e.getCause()));
                    } catch (Throwable e) {
                        return ValidationRecord.failed(mapperMethod.key(), parameters.source, throwableSummary(e));
                    }
                }
            
                private void applySchema(ValidationConfig config) {
                    if (config.schema == null || config.schema.isBlank()) {
                        return;
                    }
                    if (dataSource == null) {
                        throw new IllegalStateException("schema is configured but no DataSource bean was available.");
                    }
                    Connection connection = DataSourceUtils.getConnection(dataSource);
                    try (Statement statement = connection.createStatement()) {
                        statement.execute("set schema " + quotedIdentifier(config.schema));
                    } catch (Exception e) {
                        throw new IllegalStateException("Failed to set Dameng schema: " + config.schema, e);
                    } finally {
                        DataSourceUtils.releaseConnection(connection, dataSource);
                    }
                }

                private String quotedIdentifier(String identifier) {
                    return "\\"" + identifier.replace("\\"", "\\"\\"") + "\\"";
                }

                private Object invokeReflectively(MapperMethod mapperMethod, Object[] args) {
                    try {
                        mapperMethod.method.setAccessible(true);
                        return mapperMethod.method.invoke(mapperMethod.bean, args);
                    } catch (InvocationTargetException e) {
                        throw new MapperInvocationException(e.getTargetException());
                    } catch (Exception e) {
                        throw new MapperInvocationException(e);
                    }
                }
            
                private boolean isWriteLikeMethod(Method method) {
                    String name = method.getName().toLowerCase(Locale.ROOT);
                    return name.startsWith("insert")
                            || name.startsWith("update")
                            || name.startsWith("delete")
                            || name.startsWith("save")
                            || name.startsWith("remove")
                            || name.startsWith("merge")
                            || name.startsWith("batch")
                            || name.startsWith("truncate")
                            || name.startsWith("create")
                            || name.startsWith("drop")
                            || name.startsWith("alter");
                }
            
                private ValueResult convertScalar(String rawValue, Class<?> targetType, Type genericType) {
                    String value = unquote(rawValue == null ? "" : rawValue.trim());
                    if ("null".equalsIgnoreCase(value)) {
                        if (targetType.isPrimitive()) {
                            return ValueResult.unresolved("Cannot assign null to primitive type " + targetType.getName() + ".");
                        }
                        return ValueResult.resolved(null);
                    }
                    try {
                        if (String.class.equals(targetType)) {
                            return ValueResult.resolved(value);
                        }
                        if (Integer.class.equals(targetType) || int.class.equals(targetType)) {
                            return ValueResult.resolved(Integer.parseInt(value));
                        }
                        if (Long.class.equals(targetType) || long.class.equals(targetType)) {
                            return ValueResult.resolved(Long.parseLong(value));
                        }
                        if (Short.class.equals(targetType) || short.class.equals(targetType)) {
                            return ValueResult.resolved(Short.parseShort(value));
                        }
                        if (Byte.class.equals(targetType) || byte.class.equals(targetType)) {
                            return ValueResult.resolved(Byte.parseByte(value));
                        }
                        if (Double.class.equals(targetType) || double.class.equals(targetType)) {
                            return ValueResult.resolved(Double.parseDouble(value));
                        }
                        if (Float.class.equals(targetType) || float.class.equals(targetType)) {
                            return ValueResult.resolved(Float.parseFloat(value));
                        }
                        if (Boolean.class.equals(targetType) || boolean.class.equals(targetType)) {
                            return ValueResult.resolved(Boolean.parseBoolean(value));
                        }
                        if (BigDecimal.class.equals(targetType)) {
                            return ValueResult.resolved(new BigDecimal(value));
                        }
                        if (BigInteger.class.equals(targetType)) {
                            return ValueResult.resolved(new BigInteger(value));
                        }
                        if (LocalDate.class.equals(targetType)) {
                            return ValueResult.resolved(LocalDate.parse(value));
                        }
                        if (LocalDateTime.class.equals(targetType)) {
                            return ValueResult.resolved(LocalDateTime.parse(value));
                        }
                        if (LocalTime.class.equals(targetType)) {
                            return ValueResult.resolved(LocalTime.parse(value));
                        }
                        if (Instant.class.equals(targetType)) {
                            return ValueResult.resolved(Instant.parse(value));
                        }
                        if (UUID.class.equals(targetType)) {
                            return ValueResult.resolved(UUID.fromString(value));
                        }
                        if (targetType.isEnum()) {
                            @SuppressWarnings({"unchecked", "rawtypes"})
                            Object enumValue = Enum.valueOf((Class<? extends Enum>) targetType.asSubclass(Enum.class), value);
                            return ValueResult.resolved(enumValue);
                        }
                        return defaultValue(targetType, genericType, 0);
                    } catch (Exception e) {
                        return ValueResult.unresolved("Failed to convert configured value '" + value
                                + "' to " + targetType.getName() + ": " + e.getMessage());
                    }
                }
            
                private ValueResult defaultValue(Class<?> targetType, Type genericType, int depth) {
                    if (String.class.equals(targetType)) {
                        return ValueResult.resolved("test");
                    }
                    if (Integer.class.equals(targetType) || int.class.equals(targetType)) {
                        return ValueResult.resolved(1);
                    }
                    if (Long.class.equals(targetType) || long.class.equals(targetType)) {
                        return ValueResult.resolved(1L);
                    }
                    if (Short.class.equals(targetType) || short.class.equals(targetType)) {
                        return ValueResult.resolved((short) 1);
                    }
                    if (Byte.class.equals(targetType) || byte.class.equals(targetType)) {
                        return ValueResult.resolved((byte) 1);
                    }
                    if (Double.class.equals(targetType) || double.class.equals(targetType)) {
                        return ValueResult.resolved(1D);
                    }
                    if (Float.class.equals(targetType) || float.class.equals(targetType)) {
                        return ValueResult.resolved(1F);
                    }
                    if (Boolean.class.equals(targetType) || boolean.class.equals(targetType)) {
                        return ValueResult.resolved(true);
                    }
                    if (BigDecimal.class.equals(targetType)) {
                        return ValueResult.resolved(BigDecimal.ONE);
                    }
                    if (BigInteger.class.equals(targetType)) {
                        return ValueResult.resolved(BigInteger.ONE);
                    }
                    if (LocalDate.class.equals(targetType)) {
                        return ValueResult.resolved(LocalDate.now());
                    }
                    if (LocalDateTime.class.equals(targetType)) {
                        return ValueResult.resolved(LocalDateTime.now());
                    }
                    if (LocalTime.class.equals(targetType)) {
                        return ValueResult.resolved(LocalTime.now());
                    }
                    if (Instant.class.equals(targetType)) {
                        return ValueResult.resolved(Instant.now());
                    }
                    if (Date.class.equals(targetType)) {
                        return ValueResult.resolved(new Date());
                    }
                    if (UUID.class.equals(targetType)) {
                        return ValueResult.resolved(new UUID(0L, 1L));
                    }
                    if (Properties.class.equals(targetType)) {
                        return ValueResult.resolved(new Properties());
                    }
                    if (Optional.class.equals(targetType)) {
                        Type nestedType = firstGenericArgument(genericType);
                        ValueResult nestedValue = defaultValue(rawClass(nestedType), nestedType, depth + 1);
                        return nestedValue.resolved
                                ? ValueResult.resolved(Optional.ofNullable(nestedValue.value))
                                : ValueResult.resolved(Optional.empty());
                    }
                    if (targetType.isArray()) {
                        ValueResult componentValue = defaultValue(targetType.getComponentType(), targetType.getComponentType(), depth + 1);
                        if (!componentValue.resolved) {
                            return componentValue;
                        }
                        Object array = Array.newInstance(targetType.getComponentType(), 1);
                        Array.set(array, 0, componentValue.value);
                        return ValueResult.resolved(array);
                    }
                    if (Collection.class.isAssignableFrom(targetType)) {
                        Type nestedType = firstGenericArgument(genericType);
                        ValueResult nestedValue = defaultValue(rawClass(nestedType), nestedType, depth + 1);
                        if (!nestedValue.resolved) {
                            return nestedValue;
                        }
                        if (Set.class.isAssignableFrom(targetType)) {
                            return ValueResult.resolved(new LinkedHashSet<>(List.of(nestedValue.value)));
                        }
                        return ValueResult.resolved(new ArrayList<>(List.of(nestedValue.value)));
                    }
                    if (Map.class.isAssignableFrom(targetType)) {
                        Map<String, Object> value = new LinkedHashMap<>();
                        value.put("key", "test");
                        return ValueResult.resolved(value);
                    }
                    if (targetType.isEnum()) {
                        Object[] constants = targetType.getEnumConstants();
                        return constants.length == 0
                                ? ValueResult.unresolved("Enum has no constants: " + targetType.getName())
                                : ValueResult.resolved(constants[0]);
                    }
                    if (depth > 1) {
                        return ValueResult.unresolved("Nested object is too complex for generated parameters: " + targetType.getName());
                    }
                    return instantiatePojo(targetType, depth);
                }
            
                private ValueResult instantiatePojo(Class<?> targetType, int depth) {
                    if (targetType.isInterface() || Modifier.isAbstract(targetType.getModifiers())) {
                        return ValueResult.unresolved("Cannot instantiate parameter type: " + targetType.getName());
                    }
                    try {
                        Constructor<?> constructor = targetType.getDeclaredConstructor();
                        constructor.setAccessible(true);
                        Object instance = constructor.newInstance();
                        for (Field field : targetType.getDeclaredFields()) {
                            int modifiers = field.getModifiers();
                            if (Modifier.isStatic(modifiers) || Modifier.isFinal(modifiers)) {
                                continue;
                            }
                            ValueResult fieldValue = defaultValue(field.getType(), field.getGenericType(), depth + 1);
                            if (fieldValue.resolved) {
                                field.setAccessible(true);
                                field.set(instance, fieldValue.value);
                            }
                        }
                        return ValueResult.resolved(instance);
                    } catch (Exception e) {
                        return ValueResult.unresolved("Cannot instantiate parameter type "
                                + targetType.getName() + ": " + e.getMessage());
                    }
                }
            
                private Type firstGenericArgument(Type type) {
                    if (type instanceof ParameterizedType parameterizedType && parameterizedType.getActualTypeArguments().length > 0) {
                        return parameterizedType.getActualTypeArguments()[0];
                    }
                    return String.class;
                }
            
                private Class<?> rawClass(Type type) {
                    if (type instanceof Class<?> clazz) {
                        return clazz;
                    }
                    if (type instanceof ParameterizedType parameterizedType && parameterizedType.getRawType() instanceof Class<?> clazz) {
                        return clazz;
                    }
                    return String.class;
                }
            
                private String parameterTypeNames(Method method) {
                    return List.of(method.getParameterTypes()).stream()
                            .map(Class::getName)
                            .collect(Collectors.joining(","));
                }
            
                private Path findProjectRoot() {
                    Path current = Path.of(System.getProperty("user.dir")).toAbsolutePath().normalize();
                    while (current != null) {
                        if (Files.isRegularFile(current.resolve(CONFIG_PATH))) {
                            return current;
                        }
                        current = current.getParent();
                    }
                    throw new IllegalStateException("Could not find " + CONFIG_PATH + " from working directory.");
                }
            
                private void writeReports(Path projectRoot, List<ValidationRecord> records) throws IOException {
                    Files.createDirectories(projectRoot.resolve(".dm-adapter"));
                    Files.writeString(projectRoot.resolve(MARKDOWN_REPORT), markdown(records), StandardCharsets.UTF_8);
                    Files.writeString(projectRoot.resolve(JSON_REPORT), json(records), StandardCharsets.UTF_8);
                }
            
                private String markdown(List<ValidationRecord> records) {
                    StringBuilder markdown = new StringBuilder();
                    markdown.append("# Dameng SQL Validation Report\\n\\n");
                    markdown.append("- Passed: `").append(count(records, "PASSED")).append("`\\n");
                    markdown.append("- Failed: `").append(count(records, "FAILED")).append("`\\n");
                    markdown.append("- Skipped: `").append(count(records, "SKIPPED")).append("`\\n\\n");
                    markdown.append("| Status | Mapper Method | Parameter Source | Message |\\n");
                    markdown.append("| --- | --- | --- | --- |\\n");
                    for (ValidationRecord record : records) {
                        markdown.append("| ").append(record.status)
                                .append(" | `").append(escapeMarkdown(record.key)).append("`")
                                .append(" | ").append(escapeMarkdown(record.parameterSource))
                                .append(" | ").append(escapeMarkdown(record.message))
                                .append(" |\\n");
                    }
                    return markdown.toString();
                }
            
                private long count(List<ValidationRecord> records, String status) {
                    return records.stream().filter(record -> status.equals(record.status)).count();
                }
            
                private String json(List<ValidationRecord> records) {
                    StringBuilder json = new StringBuilder();
                    json.append("{\\n  \\"records\\": [\\n");
                    for (int i = 0; i < records.size(); i++) {
                        ValidationRecord record = records.get(i);
                        json.append("    {")
                                .append("\\"status\\": \\"").append(escapeJson(record.status)).append("\\", ")
                                .append("\\"key\\": \\"").append(escapeJson(record.key)).append("\\", ")
                                .append("\\"parameterSource\\": \\"").append(escapeJson(record.parameterSource)).append("\\", ")
                                .append("\\"message\\": \\"").append(escapeJson(record.message)).append("\\"")
                                .append("}");
                        if (i + 1 < records.size()) {
                            json.append(",");
                        }
                        json.append("\\n");
                    }
                    json.append("  ]\\n}\\n");
                    return json.toString();
                }
            
                private String resultSummary(Object result) {
                    if (result == null) {
                        return "Returned null.";
                    }
                    if (result instanceof Collection<?> collection) {
                        return "Returned collection size " + collection.size() + ".";
                    }
                    if (result instanceof Map<?, ?> map) {
                        return "Returned map size " + map.size() + ".";
                    }
                    return "Returned " + result.getClass().getName() + ".";
                }
            
                private String throwableSummary(Throwable throwable) {
                    if (throwable == null) {
                        return "Unknown failure.";
                    }
                    String message = throwable.getMessage();
                    return throwable.getClass().getName() + (message == null || message.isBlank() ? "" : ": " + message);
                }
            
                private String escapeMarkdown(String value) {
                    return value == null ? "" : value.replace("|", "\\\\|").replace("\\n", " ");
                }
            
                private String escapeJson(String value) {
                    if (value == null) {
                        return "";
                    }
                    return value.replace("\\\\", "\\\\\\\\")
                            .replace("\\"", "\\\\\\"")
                            .replace("\\n", "\\\\n")
                            .replace("\\r", "\\\\r")
                            .replace("\\t", "\\\\t");
                }
            
                private String unquote(String value) {
                    if (value.length() >= 2
                            && ((value.startsWith("\\"") && value.endsWith("\\""))
                            || (value.startsWith("'") && value.endsWith("'")))) {
                        return value.substring(1, value.length() - 1);
                    }
                    return value;
                }
            
                private static final class ValidationConfig {
                    private String schema = "";
                    private final Map<String, List<String>> methodArgs = new LinkedHashMap<>();
                    private final Set<String> excludedMethods = new LinkedHashSet<>();
            
                    static ValidationConfig load(Path path) throws IOException {
                        ValidationConfig config = new ValidationConfig();
                        if (!Files.isRegularFile(path)) {
                            return config;
                        }
                        String section = "";
                        String currentMethod = null;
                        for (String line : Files.readAllLines(path, StandardCharsets.UTF_8)) {
                            String trimmed = line.trim();
                            if (trimmed.isBlank() || trimmed.startsWith("#")) {
                                continue;
                            }
                            if (!line.startsWith(" ") && trimmed.startsWith("schema:")) {
                                config.schema = config.scalar(trimmed.substring("schema:".length()));
                                section = "";
                                currentMethod = null;
                                continue;
                            }
                            if (!line.startsWith(" ") && "methods:".equals(trimmed)) {
                                section = "methods";
                                currentMethod = null;
                                continue;
                            }
                            if (!line.startsWith(" ") && "excludedMethods:".equals(trimmed)) {
                                section = "excludedMethods";
                                currentMethod = null;
                                continue;
                            }
                            if ("excludedMethods".equals(section) && trimmed.startsWith("- ")) {
                                config.excludedMethods.add(config.scalar(trimmed.substring(2)));
                                continue;
                            }
                            if ("methods".equals(section)) {
                                if (line.startsWith("  ") && !line.startsWith("    ") && trimmed.endsWith(":")) {
                                    currentMethod = trimmed.substring(0, trimmed.length() - 1).trim();
                                    config.methodArgs.computeIfAbsent(currentMethod, ignored -> new ArrayList<>());
                                    continue;
                                }
                                if (currentMethod != null && trimmed.startsWith("- ")) {
                                    config.methodArgs.computeIfAbsent(currentMethod, ignored -> new ArrayList<>())
                                            .add(config.scalar(trimmed.substring(2)));
                                }
                            }
                        }
                        return config;
                    }
            
                    boolean excludes(String methodKey) {
                        if (excludedMethods.contains(methodKey)) {
                            return true;
                        }
                        int lastDot = methodKey.lastIndexOf('.');
                        return lastDot > 0 && excludedMethods.contains(methodKey.substring(0, lastDot) + ".*");
                    }
            
                    private String scalar(String value) {
                        String trimmed = value.trim();
                        if (trimmed.length() >= 2
                                && ((trimmed.startsWith("\\"") && trimmed.endsWith("\\""))
                                || (trimmed.startsWith("'") && trimmed.endsWith("'")))) {
                            return trimmed.substring(1, trimmed.length() - 1);
                        }
                        return trimmed;
                    }
                }
            
                private static final class MapperMethod {
                    private final Object bean;
                    private final Class<?> mapperInterface;
                    private final Method method;
            
                    private MapperMethod(Object bean, Class<?> mapperInterface, Method method) {
                        this.bean = bean;
                        this.mapperInterface = mapperInterface;
                        this.method = method;
                    }
            
                    private String key() {
                        return mapperInterface.getName() + "." + method.getName();
                    }
                }
            
                private static final class ParameterResolution {
                    private final boolean resolved;
                    private final String source;
                    private final Object[] args;
                    private final String message;
            
                    private ParameterResolution(boolean resolved, String source, Object[] args, String message) {
                        this.resolved = resolved;
                        this.source = source;
                        this.args = args;
                        this.message = message;
                    }
            
                    static ParameterResolution resolved(String source, Object[] args) {
                        return new ParameterResolution(true, source, args, "");
                    }
            
                    static ParameterResolution unresolved(String source, String message) {
                        return new ParameterResolution(false, source, new Object[0], message);
                    }
                }
            
                private static final class ValueResult {
                    private final boolean resolved;
                    private final Object value;
                    private final String message;
            
                    private ValueResult(boolean resolved, Object value, String message) {
                        this.resolved = resolved;
                        this.value = value;
                        this.message = message;
                    }
            
                    static ValueResult resolved(Object value) {
                        return new ValueResult(true, value, "");
                    }
            
                    static ValueResult unresolved(String message) {
                        return new ValueResult(false, null, message);
                    }
                }
            
                private static final class ValidationRecord {
                    private final String status;
                    private final String key;
                    private final String parameterSource;
                    private final String message;
            
                    private ValidationRecord(String status, String key, String parameterSource, String message) {
                        this.status = status;
                        this.key = key;
                        this.parameterSource = parameterSource;
                        this.message = message;
                    }
            
                    static ValidationRecord passed(String key, String parameterSource, String message) {
                        return new ValidationRecord("PASSED", key, parameterSource, message);
                    }
            
                    static ValidationRecord failed(String key, String parameterSource, String message) {
                        return new ValidationRecord("FAILED", key, parameterSource, message);
                    }
            
                    static ValidationRecord skipped(String key, String parameterSource, String message) {
                        return new ValidationRecord("SKIPPED", key, parameterSource, message);
                    }
                }
            
                private static final class MapperInvocationException extends RuntimeException {
                    private MapperInvocationException(Throwable cause) {
                        super(cause);
                    }
                }
            }
            """;
}
