package com.github.dmadapter.cli;

import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.stream.Collectors;

record TableKeyMetadata(
        String tableName,
        List<TableConstraint> constraints,
        boolean tableFound,
        Set<String> autoGeneratedColumns
) {
    TableKeyMetadata(String tableName, List<TableConstraint> constraints) {
        this(tableName, constraints, true, Set.of());
    }

    TableKeyMetadata {
        tableName = tableName == null ? "" : tableName.trim();
        constraints = List.copyOf(constraints == null ? List.of() : constraints);
        autoGeneratedColumns = autoGeneratedColumns == null
                ? Set.of()
                : autoGeneratedColumns.stream()
                        .filter(column -> column != null && !column.isBlank())
                        .map(column -> column.trim().toLowerCase(Locale.ROOT))
                        .collect(Collectors.toUnmodifiableSet());
    }

    List<TableConstraint> primaryKeys() {
        return constraints.stream()
                .filter(constraint -> constraint.type() == TableConstraint.ConstraintType.PRIMARY_KEY)
                .toList();
    }

    List<TableConstraint> uniqueKeys() {
        return constraints.stream()
                .filter(constraint -> constraint.type() == TableConstraint.ConstraintType.UNIQUE_KEY)
                .toList();
    }
}
