package com.github.dmadapter.cli;

import com.github.dmadapter.mybatis.SqlRewriteConfig;

import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

final class UpsertKeyInference {
    static final String RESOLUTION_ORIGINAL_SQL_NO_USABLE_CONFLICT_KEY =
            SqlRewriteConfig.ORIGINAL_SQL_NO_USABLE_CONFLICT_KEY;
    static final String RESOLUTION_INSERT_IGNORE_AS_PLAIN_INSERT =
            "INSERT_IGNORE_AS_PLAIN_INSERT";
    static final String RESOLUTION_MANUAL_KEY_COLUMNS_REQUIRED =
            SqlRewriteConfig.MANUAL_KEY_COLUMNS_REQUIRED;
    static final String RESOLUTION_METADATA_UNAVAILABLE =
            SqlRewriteConfig.KEY_METADATA_UNAVAILABLE;

    Optional<InferenceResult> infer(RewriteConfigCandidate candidate, TableKeyMetadata metadata) {
        if (metadata == null || !metadata.tableFound()) {
            return Optional.of(InferenceResult.unresolved(
                    RESOLUTION_METADATA_UNAVAILABLE,
                    "No table key metadata was available for table "
                            + candidate.tableName() + "."
            ));
        }
        if (normalizedColumns(candidate.insertColumns()).isEmpty()) {
            return Optional.of(InferenceResult.unresolved(
                    RESOLUTION_MANUAL_KEY_COLUMNS_REQUIRED,
                    "Could not determine INSERT columns for "
                            + candidate.methodKey() + "; keyColumns must be configured manually."
            ));
        }
        if (candidate.insertIgnore() && hasNoReachableConflictKey(candidate, metadata)) {
            return Optional.of(InferenceResult.unresolved(
                    RESOLUTION_INSERT_IGNORE_AS_PLAIN_INSERT,
                    "INSERT IGNORE has no reachable primary or unique key conflict for "
                            + candidate.methodKey()
                            + "; it can be converted to a plain INSERT."
            ));
        }
        if (metadata.constraints().isEmpty()) {
            return Optional.of(InferenceResult.unresolved(
                    RESOLUTION_ORIGINAL_SQL_NO_USABLE_CONFLICT_KEY,
                    "No primary key or unique key metadata was found for table "
                            + candidate.tableName() + "."
            ));
        }

        List<TableConstraint> usablePrimaryKeys = usableConstraints(candidate, metadata.primaryKeys());
        if (usablePrimaryKeys.size() == 1) {
            return Optional.of(InferenceResult.inferred(
                    usablePrimaryKeys.get(0).columns(),
                    "primary key " + usablePrimaryKeys.get(0).name()
            ));
        }
        if (usablePrimaryKeys.size() > 1) {
            return Optional.of(InferenceResult.unresolved(
                    RESOLUTION_MANUAL_KEY_COLUMNS_REQUIRED,
                    "Multiple primary key metadata rows matched table "
                            + candidate.tableName() + "."
            ));
        }

        List<TableConstraint> usableUniqueKeys = usableConstraints(candidate, metadata.uniqueKeys());
        if (usableUniqueKeys.size() == 1) {
            return Optional.of(InferenceResult.inferred(
                    usableUniqueKeys.get(0).columns(),
                    "unique key " + usableUniqueKeys.get(0).name()
            ));
        }
        if (usableUniqueKeys.size() > 1) {
            return Optional.of(InferenceResult.unresolved(
                    RESOLUTION_MANUAL_KEY_COLUMNS_REQUIRED,
                    "Multiple unique keys matched INSERT columns for table "
                            + candidate.tableName() + ": " + describe(usableUniqueKeys) + "."
            ));
        }

        return Optional.of(InferenceResult.unresolved(
                RESOLUTION_ORIGINAL_SQL_NO_USABLE_CONFLICT_KEY,
                "No primary key or unique key columns are fully present in INSERT columns for "
                        + candidate.methodKey() + "."
        ));
    }

    private boolean hasNoReachableConflictKey(
            RewriteConfigCandidate candidate,
            TableKeyMetadata metadata
    ) {
        if (metadata.constraints().isEmpty()) {
            return true;
        }
        Set<String> insertedColumns = normalizedColumns(candidate.insertColumns());
        Set<String> autoGeneratedColumns = metadata.autoGeneratedColumns();
        return metadata.constraints().stream().allMatch(constraint ->
                constraint.columns().stream()
                        .map(DamengMetadataReader::normalizeIdentifier)
                        .anyMatch(column -> !insertedColumns.contains(column)
                                && autoGeneratedColumns.contains(column))
        );
    }

    private List<TableConstraint> usableConstraints(RewriteConfigCandidate candidate, List<TableConstraint> constraints) {
        Map<String, String> insertedColumns = normalizedColumnsByOriginal(candidate.insertColumns());
        return constraints.stream()
                .filter(constraint -> !constraint.columns().isEmpty())
                .map(constraint -> candidateColumnConstraint(constraint, insertedColumns))
                .flatMap(Optional::stream)
                .toList();
    }

    private Set<String> normalizedColumns(List<String> columns) {
        Set<String> normalized = new LinkedHashSet<>();
        for (String column : columns) {
            String clean = DamengMetadataReader.normalizeIdentifier(column);
            if (!clean.isBlank() && clean.matches("[a-zA-Z_][a-zA-Z0-9_]*")) {
                normalized.add(clean);
            }
        }
        return normalized;
    }

    private Map<String, String> normalizedColumnsByOriginal(List<String> columns) {
        Map<String, String> normalized = new LinkedHashMap<>();
        for (String column : columns) {
            String clean = DamengMetadataReader.normalizeIdentifier(column);
            if (!clean.isBlank() && clean.matches("[a-zA-Z_][a-zA-Z0-9_]*")) {
                normalized.putIfAbsent(clean, column);
            }
        }
        return normalized;
    }

    private Optional<TableConstraint> candidateColumnConstraint(
            TableConstraint constraint,
            Map<String, String> insertedColumns
    ) {
        List<String> candidateColumns = constraint.columns().stream()
                .map(DamengMetadataReader::normalizeIdentifier)
                .map(insertedColumns::get)
                .toList();
        if (candidateColumns.stream().anyMatch(column -> column == null || column.isBlank())) {
            return Optional.empty();
        }
        return Optional.of(new TableConstraint(constraint.name(), constraint.type(), candidateColumns));
    }

    private String describe(List<TableConstraint> constraints) {
        return constraints.stream()
                .map(constraint -> constraint.name() + constraint.columns())
                .toList()
                .toString();
    }

    record InferenceResult(
            boolean inferred,
            List<String> keyColumns,
            String source,
            String resolutionCode,
            String reason
    ) {
        static InferenceResult inferred(List<String> keyColumns, String source) {
            return new InferenceResult(true, keyColumns, source == null ? "" : source, "", "");
        }

        static InferenceResult unresolved(String resolutionCode, String reason) {
            return new InferenceResult(
                    false,
                    List.of(),
                    "",
                    resolutionCode == null ? "" : resolutionCode,
                    reason == null ? "" : reason
            );
        }

        InferenceResult {
            keyColumns = List.copyOf(keyColumns == null ? List.of() : keyColumns);
        }
    }
}
