-- 这些是已在 53 达梦环境验证为不能直接执行的 MySQL 语法示例。
-- 验证目标：jdbc:dm://192.168.1.53:5236，用户 SYSDBA，验证日期 2026-06-30。
-- 每个 Dxx 小节都与 dm.sql 中相同编号的小节一一对应。
-- 说明：
-- 1. CONCAT、CONCAT_WS、LIMIT、反引号标识符、FIND_IN_SET、IF、IFNULL、
--    DATE_FORMAT、STR_TO_DATE、UPDATE JOIN、DELETE JOIN、JSON_EXTRACT、
--    JSON_OBJECT 以及 ALTER TABLE ... AUTO_INCREMENT = n 已在 53 达梦环境执行通过，
--    因此这里不把它们列为必须改写项。
-- 2. 下方公共建表和数据准备语句采用 MySQL 写法，用于在 MySQL 环境运行这些示例。

DROP TABLE IF EXISTS DMADAPTER_DIFF_BASIC;
DROP TABLE IF EXISTS DMADAPTER_DIFF_KV;
DROP TABLE IF EXISTS DMADAPTER_DIFF_DDL;
DROP TABLE IF EXISTS DMADAPTER_DIFF_TOUCH;

CREATE TABLE DMADAPTER_DIFF_BASIC (
    id INT PRIMARY KEY,
    name VARCHAR(50),
    status VARCHAR(20),
    csv VARCHAR(100),
    create_time TIMESTAMP,
    amount VARCHAR(20),
    flag INT
);

INSERT INTO DMADAPTER_DIFF_BASIC(id, name, status, csv, create_time, amount, flag) VALUES
(1, 'alice', 'ACTIVE', '1,2,10', '2026-06-30 10:11:12', '12.30', 1),
(2, 'bob', 'INACTIVE', '3,4', '2026-06-29 09:00:00', '8', 0);

CREATE TABLE DMADAPTER_DIFF_KV (
    id INT PRIMARY KEY,
    val VARCHAR(50)
);

INSERT INTO DMADAPTER_DIFF_KV(id, val) VALUES (1, 'old');

-- D01：MySQL 双引号字符串字面量。达梦会把双引号内容当作标识符。
SELECT id
FROM DMADAPTER_DIFF_BASIC
WHERE status = "ACTIVE";

-- D02：MySQL 单引号查询别名。
SELECT COUNT(*) 'totalCount'
FROM DMADAPTER_DIFF_BASIC;

-- D03：MySQL GROUP_CONCAT 聚合函数。
SELECT GROUP_CONCAT(name ORDER BY name SEPARATOR ',') AS names
FROM DMADAPTER_DIFF_BASIC;

-- D04：MySQL REGEXP 正则操作符。
SELECT id
FROM DMADAPTER_DIFF_BASIC
WHERE name REGEXP '^a';

-- D05：MySQL DATE_ADD 搭配 INTERVAL 的日期加法。
SELECT DATE_ADD(create_time, INTERVAL 1 DAY) AS next_day
FROM DMADAPTER_DIFF_BASIC;

-- D06：MySQL DATE_SUB 搭配 INTERVAL 的日期减法。
SELECT DATE_SUB(create_time, INTERVAL 1 DAY) AS prev_day
FROM DMADAPTER_DIFF_BASIC;

-- D07：MySQL CONVERT(expr, DECIMAL(p,s)) 类型转换。
SELECT CONVERT(amount, DECIMAL(10, 2)) AS amount_num
FROM DMADAPTER_DIFF_BASIC;

-- D08：MySQL CAST(... AS UNSIGNED) 无符号数转换。
SELECT CAST(id AS UNSIGNED) AS id_num
FROM DMADAPTER_DIFF_BASIC;

-- D09：MySQL 用户变量行号写法。
SELECT @rn := @rn + 1 AS rn, id
FROM DMADAPTER_DIFF_BASIC, (SELECT @rn := 0) r
ORDER BY id;

-- D10：MySQL ON DUPLICATE KEY UPDATE 写法。
INSERT INTO DMADAPTER_DIFF_KV(id, val)
VALUES (1, 'new')
ON DUPLICATE KEY UPDATE val = VALUES(val);

-- D11：MySQL REPLACE INTO 写法。
REPLACE INTO DMADAPTER_DIFF_KV(id, val)
VALUES (1, 'replace_new');

-- D12：MySQL INSERT IGNORE 写法。
INSERT IGNORE INTO DMADAPTER_DIFF_KV(id, val)
VALUES (1, 'ignored');

-- D13：MySQL UPDATE ... ORDER BY ... LIMIT 写法。
UPDATE DMADAPTER_DIFF_BASIC
SET status = 'NEW'
ORDER BY id
LIMIT 1;

-- D14：MySQL DESCRIBE 查看表结构。
DESCRIBE DMADAPTER_DIFF_BASIC;

-- D15：MySQL SHOW TABLES 查看表清单。
SHOW TABLES;

-- D16：MySQL information_schema 元数据表和 DATABASE() 函数。
SELECT COUNT(*)
FROM information_schema.tables
WHERE table_schema = DATABASE()
  AND table_name = 'DMADAPTER_DIFF_BASIC';

-- D17：MySQL DATABASE() / SCHEMA() 当前库函数。
SELECT DATABASE(), SCHEMA();

-- D18：MySQL PERIOD_DIFF 年月差函数。
SELECT PERIOD_DIFF(202606, 202501) AS month_diff;

-- D19：MySQL MAKEDATE 按年份和年内天数构造日期。
SELECT MAKEDATE(2026, 181) AS the_day;

-- D20：MySQL INSERT ... VALUE 单数写法。
INSERT INTO DMADAPTER_DIFF_KV(id, val)
VALUE (3, 'v3');

-- D21：MySQL 建表内表注释、列注释、普通 KEY、USING BTREE 和表选项。
CREATE TABLE DMADAPTER_DIFF_DDL (
    id INT COMMENT '编号',
    name VARCHAR(20),
    KEY idx_dmadapter_diff_ddl_name (name) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '表注释';

-- D22：MySQL ON UPDATE CURRENT_TIMESTAMP 列属性。
CREATE TABLE DMADAPTER_DIFF_TOUCH (
    id INT PRIMARY KEY,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
